//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoI_Libreria.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

    public partial class Prestamos
    {
        public int Id { get; set; }
       
        [Display(Name = "Identificación de la persona")]
        [Required(ErrorMessage = "El campo Identificación de la persona es requerido.")]
        public Nullable<int> IdPersona { get; set; }

        [Display(Name = "Identificación del libro")]
        [Required(ErrorMessage = "El campo Identificación del libro es requerido.")]
        public Nullable<int> IdLibro { get; set; }

        [Display(Name = "Fecha del préstamo")]
        //[Required(ErrorMessage = "El campo Fecha del préstamo es requerido.")]
        public Nullable<System.DateTime> FechaPrestamo { get; set; }

        [Display(Name = "Fecha de Devolución")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [FechaDevolucionValida(ErrorMessage = "La Fecha de la devolución debe ser mayor o igual a la fecha actual")]
        public DateTime FechaDevolucion { get; set; }



        [Display(Name = "Fecha de Entrega")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? FechaDevolucionReal { get; set; }


        //public Nullable<System.DateTime> FechaDevolucion { get; set; }

        [Required(ErrorMessage = "El campo Devuelto es requerido.")]
        public Nullable<bool> Devuelto { get; set; }
        
     
        public virtual Libros Libros { get; set; }

        public virtual Personas Personas { get; set; }

    }

   
public class FechaDevolucionValidaAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            DateTime fechaDevolucion = (DateTime)value;

            // Obtener el objeto actual
            var prestamos = validationContext.ObjectInstance as Prestamos;

            // Validar solo en el caso de ingreso (nuevo registro)
            if (prestamos != null && prestamos.Id == 0)
            {
                if (fechaDevolucion.Date < DateTime.Today)
                {
                    return new ValidationResult(ErrorMessage);
                }
            }

            return ValidationResult.Success;
        }
    }
}

